const { PrismaClient } = await import('@prisma/client')
const p = new PrismaClient()
const stores = await p.lottoDrawStore.count()
const draws = await p.lottoDraw.count()
console.log(`LottoDrawStore: ${stores}개`)
console.log(`LottoDraw: ${draws}회차`)
const sample = await p.lottoDrawStore.findMany({ take: 3, orderBy: { round: 'desc' } })
console.log('최신 샘플:', sample.map(s => `${s.round}회 ${s.name}`).join(', '))
await p.$disconnect()
